# Generated by Django 4.1 on 2022-09-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.CharField(max_length=12, verbose_name='Seria')),
                ('num', models.PositiveIntegerField(verbose_name='Card number')),
                ('date_of_manufacture', models.DateField(verbose_name='Вate of manufacture')),
                ('end_date', models.DateField(verbose_name='End date of activity')),
                ('use_date', models.DateField(auto_now=True, verbose_name='Date of use')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Amount')),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Not valid', 'Not valid')], default='Valid', max_length=9, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-date_of_manufacture'],
            },
        ),
        migrations.CreateModel(
            name='CardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
    ]
