# Generated by Django 4.1 on 2022-09-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_of_manufacture',
            field=models.DateField(verbose_name='Date of manufacture'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cards.card'),
        ),
    ]
